spring:
  datasource:
    name: testdb
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS CONTACTS_API
      #url: jdbc:h2:testdb;AUTO_SERVER=TRUE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS CONTACTS_API
    username: user
  jpa:
    properties.hibernate.dialect:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console